spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/guerreiro_db
spring.datasource.username=eugenio
spring.datasource.password=

# Inicialização SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false